/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieIdIndexRouteImport } from './routes/movie.$id/index'
import { Route as MovieIdTrailerRouteImport } from './routes/movie.$id/trailer'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdIndexRoute = MovieIdIndexRouteImport.update({
  id: '/movie/$id/',
  path: '/movie/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdTrailerRoute = MovieIdTrailerRouteImport.update({
  id: '/movie/$id/trailer',
  path: '/movie/$id/trailer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id/trailer': typeof MovieIdTrailerRoute
  '/movie/$id': typeof MovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id/trailer': typeof MovieIdTrailerRoute
  '/movie/$id': typeof MovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/movie/$id/trailer': typeof MovieIdTrailerRoute
  '/movie/$id/': typeof MovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/search'
    | '/movie/$id/trailer'
    | '/movie/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/search' | '/movie/$id/trailer' | '/movie/$id'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/search'
    | '/movie/$id/trailer'
    | '/movie/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  MovieIdTrailerRoute: typeof MovieIdTrailerRoute
  MovieIdIndexRoute: typeof MovieIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id/': {
      id: '/movie/$id/'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id/trailer': {
      id: '/movie/$id/trailer'
      path: '/movie/$id/trailer'
      fullPath: '/movie/$id/trailer'
      preLoaderRoute: typeof MovieIdTrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  MovieIdTrailerRoute: MovieIdTrailerRoute,
  MovieIdIndexRoute: MovieIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
